version: '3.8'

# 1. Определяем нашу собственную сеть здесь
networks:
  xabar-net:
    driver: bridge
  vs_code_default:
    external: true

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xabar_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xabar-net # 2. Подключаем сервис к нашей сети

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      # ... ваша конфигурация Kafka ...
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - xabar-net
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 15 # Увеличим количество попыток на всякий случай

  api:
    build:
      context: ./apps/api # Убедитесь, что путь ./api, а не ./apps/api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      kafka:
        condition: service_healthy # Ждем, пока Kafka будет готова
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/xabar_dev"
      JWT_SECRET: "your-super-secret-key"
      KAFKA_BROKERS: "kafka:9092" # Передаем адрес брокера через переменную
    command: sh -c "npx prisma migrate deploy && npm run start"
    networks:
      - xabar-net

  worker:
    build:
      context: ./apps/workers/email-worker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      kafka:
        condition: service_healthy # Ждем, пока Kafka будет готова
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/xabar_dev"
      KAFKA_BROKERS: "kafka:9092" # Передаем адрес брокера через переменную
    command: "npm run start"
    networks:
      - xabar-net

  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: Dockerfile
    restart: always
    # Публикуем порт для дашборда, чтобы Cloudflare Tunnel мог к нему подключиться
    # Туннель будет указывать на <ip_вашего_pi>:3001
    depends_on:
      - api
    networks:
      - xabar-net
      - vs_code_default

volumes:
  postgres_data: