services:
  kafka:
    # Используем образ от Bitnami - он отлично подходит для KRaft
    image: 'bitnami/kafka:latest'
    ports:
      # Порт для подключения клиентов ИЗВНЕ Docker-сети (наш NestJS)
      - '9092:9092'
    environment:
      # --- KRaft-режим без ZooKeeper ---
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # --- Настройка слушателей (listeners) ---
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # --- Базовые настройки брокера ---
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Автоматически создавать топики, если их нет
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true